### ISSUE TITLE
AtlasDB does not actually use baseline checkstyle

### ISSUE THREAD

**Issue by gsheasby** [palantir/atlasdb#3297]
Filing for tracking.

Intellij's configured checkstyle (Baseline checkstyle) does not match `./gradlew check`. Instead, the gradle function runs a very restricted set of rules that pre-dates baseline.

There are ~2300 errors according to baseline 0.18, and ~11,500 according to baseline 0.20. For 0.18, most of the errors are confined to a few projects with a lot of legacy code that we didn't get to in the baseline bash last year (see #334).

- [x] Step 1 (PR #3292) - Revert back to baseline 0.18
- [x] Step 2 (PR #3301) - Switch gradle to actually use baseline, and fix or suppress the ~170 errors that will appear
- [x] Step 2.25 (PR #3308) - Fix the 80 or so errors in impl-shared
- [ ] Step 2.5 (optional) - Reduce the number of suppressed projects
- [x] Step 3 (forked in PR #3300) - Upgrade to baseline 0.20 (potentially involves changing copyright and import order of every file)

Suppressed projects and their errors (for baseline 0.18)
- [ ] atlasdb-client | 379 |
- [x] atlasdb-client-protobufs | 0 | Generated code
- [ ] atlasdb-commons | 540 |  
- [ ] atlasdb-console | 90 |  
- [x] atlasdb-dbkvs-hikari | 41 |  #3380
- [x] atlasdb-jdbc | 124 | Deprecated
- [x] atlasdb-jdbc-tests | 1 | Deprecated
- [x] atlasdb-service-server | 0 | Deleted!
- [ ] cassandra-partitioner | 62 | 
- [ ] commons-db | 618 |  
- [x] commons-executors | 17 |  #3341
- [ ] leader-election-impl | 138 |  
- [ ] lock-impl | 159 |  
- [x] profile-client-protobufs | 0 |  Generated code
- [x] timestamp-impl | 22 |  #3341

**Comment by gmaretic** [comment]
I think we did as much as is reasonable here, also we are on 0.30.0 now: https://github.com/palantir/atlasdb/blob/c4845828b3f9c28f79a7cafacdf784069e5efac3/build.gradle#L18
