### ISSUE TITLE
Fix Cruft Caused by DbKvs Port

### ISSUE THREAD

**Issue by rjullman** [palantir/atlasdb#504]
# Outstanding Tasks From DBKvs Port
- [ ] Code Cleanup/Improvements
  - [ ] Fix/Reorganize Atlas Configuration of DbKvs related things https://github.com/palantir/atlasdb/pull/545
    - [ ] Optional config should be required (needs internal code change)
    - [x] **"relational" config type with different driver types ("postgres", "oracle", etc.)** 
  - [ ] Respond to all comments on past commits (those listed in the ordering plan)
  - [ ] Remove Internal Utils (e.g. dbcommons)
  - [ ] Replace SqlConnectionImpl with SQL Library (and remove PalantirSqlConnection)
  - [ ] Refactor table names (both regular and overflow) https://github.com/palantir/atlasdb/pull/533 (non-overflow changes)
  - [ ] ConnectionConfig inherited DBConfig's cruft (in the name of stability) https://github.com/palantir/atlasdb/pull/545
  - [ ] **Do not require seeding (also must address internal table prefixes and oracle array struct prefixes)** https://github.com/palantir/atlasdb/pull/567
  - [ ] Should we prefix 'hidden' tables?  The main case being _metadata table?
  - [ ] Consolidate private SQL table prefix applying functions - e.g. prefixedTableName()
  - [ ] Remove DbKvs public constructor (make all code paths to create DbKvs the same)
  - [ ] Remove ConnectionAwareDbKvs (see InDbTimestampBoundStore improvements below) 
  - [ ] Instantiation of the SqlConnection for OSS dbkvs code path requires a timestamp supplier that is entirely unused, the impl should be refactored to have a version that does not require the timestamp supplier.
- [ ] Code Ownership
  - [ ] Push in needed tests
  - [ ] Push out unneeded code/tests +1
  - [ ] Dependency tree cleanup (e.g. are we happy with atlasdb-dbkvs-hikari?)
  - [ ] Make alternatives to certain classes (and push back that class)
    - [x] DBMgrConfigurationException.java
    - [ ] JdbcConfig.java https://github.com/palantir/atlasdb/pull/545
- [ ] Oveflow Tables
  - [ ] Give the correct level of configuration (probably fewer options)
  - [ ] Use native Overflow support
  - [ ] Remove Oracle metadata's inclusion of table_size
- [ ] Configuration
  - [ ] Iron out OracleKVS Story (e.g. unspecified "type" value in OracleDbKVSConfig)
  - [ ] General config complications (e.g. essentially specifying DBType twice)
  - [x] **~~Table prefix ("a_" vs "atlas_") or~~ no default prefix** https://github.com/palantir/atlasdb/pull/567
  - [ ] Cassandra configuration live reload (e.g. membership)
- [ ] Overarching Improvements
  - [ ] InDbTimestampBoundStore should use DbKvs directly (then we can remove ConnectionAwareDbKvs)
  - [ ] Figure out plans for H2 in memory support
  - [ ] Determine intended level of support for Postgres, notably `CREATE TABLE IF NOT EXISTS` in InDbTimestampBoundStore

**In bold are things that we should address (at least think about) before allowing people to use a dbkvs beta**
# PR Ordering Plan
- [x] Wholesale Move Code to Open Source --> https://github.com/palantir/atlasdb/pull/467
- [x] Open Source Core SQL Driver --> https://github.com/palantir/atlasdb/pull/497
- [x] Open Source Hikari Pooling --> https://github.com/palantir/atlasdb/pull/507
- [x] Make Hikari Pooling Open-source Instantiable --> https://github.com/palantir/atlasdb/pull/520
- [x] Handle internal table prefixes and overflow tables --> https://github.com/palantir/atlasdb/pull/533 and https://github.com/palantir/atlasdb/pull/540 (additional fixes)
- [x] Add testing infrastructure --> https://github.com/palantir/atlasdb/pull/567
- [x] Final cleanup and allow the instantiation from Open-source config --> https://github.com/palantir/atlasdb/pull/545
- [x] Fix connection closing issues / table creation of _timestamp --> #606

**Comment by rjullman** [comment]
note to self: fix urlSuffix stuff in DatabaseConfig.java

**Comment by jboreiko** [comment]
- [ ] generalize the checkpointer test and add to kvs test suites

**Comment by gsheasby** [comment]
- [ ] there are still a few things odd with the DB KVS config. The following properties are under DdlConfig, but really have nothing to do with DDL, but are used for DML reads and writes:

    ddl:
      poolSize: 64 # thread pool size for DB KVS executor
      fetchBatchSize: 256 # large read batching into separate queries
      mutationBatchCount: 1000 # put batch partitioning
      mutationBatchSizeBytes: 2097152 # put batch partitioning

**Comment by gsheasby** [comment]
@jboreiko, could you update this with what other things have been fixed, and figure out what we actually want to do here?

**Comment by berler** [comment]
The current DBKVS yaml config format also doesn't really make much sense; it combines two completely different things: the Hikari pool config, and the connection config (for individual DB connections). Ideally these would be two separate config blocks to make it clear what is actually being configured.  Fixing this would be an API breaking change.  Also internally the naming on methods and such is inconsistent and confusing (for example there are methods like "getHikariProperties" that are actually not pertaining to Hikari, but simply passed into Hikari and used as Connection parameters).

In my most recent PR I added a connectionParameters block to the config which allows arbitrary JDBC params, the issue is that we still have config outside that block that actually end up as connectionParamters.  The change here would be to remove all parameters that are outside that block and instead rely on setting them correctly in the connectionParameters block.  Remaining parameters that actually pertain to the hikari pool should be put in their own "hikari" block in the config (or this could be named "hikariPoolConfig" etc) rather than being at effectively the top level.

In other words, the current config looks like this:

```yaml
atlasdb:
  keyValueService:
    type: relational
    ddl:
      type: postgres
    connection:
      type: postgres
      host: postgres.palantir.dev
      port: 1000
      dbName: test
      dbLogin: test
      dbPassword: testpassword
      connectionTimeoutSeconds: 5
      socketTimeoutSeconds: 30
      connectionParameters:
        defaultRowFetchSize: 1000
```

My proposed change would be to do this:

```yaml
atlasdb:
  keyValueService:
    type: relational
    hikariPoolConfig:
      # IMPORTANT: see the official hikari documentation for what these mean. These params are completely different
      # from JDBC params. This section can be left out entirely if defaults are acceptable.
      minimumIdle: 8
      maximumPoolSize: 256
      maxLifetime: 1800000
      idleTimeout: 600000
      connectionTimeout: 30000
      leakDetectionThreshold: 0
    databaseConnectionConfig:
      # parameters that pertain to standard DB connections (not the hikari pool)
      # type, host, port, and database are *not* jdbc params but rather get used to construct the jdbc URL
      # (other params could be here, for example oracle also has "sid")
      type: postgres
      host: postgres.palantir.dev
      port: 1000
      database: test
      jdbcParameters:
        # jdbc parameters passed in exactly as is
        user: test
        password: testpassword
        socketTimeout: 100
        defaultRowFetchSize: 1000
```

Other notes about my proposed change: the "ddl" block is not necessary, the ddl type can be inferred from the type on the connection (in the current config it would be broken if you didn't make them match).

**Comment by jboreiko** [comment]
Unfortunately most of those things have not been resolved.  I added a single check for the removal of DBMgrCE.java.  Some of the oracle stuff going in will resolve a few of these but most of them remain open.  Not sure we'll be able to get to all of it, may want to chunk into higher pri tickets after Oracle stuff merges and we have the two (three with H2) working impls of DBKVS.  

Quite of few of them also would require associated changes in the large internal product so we should keep that in mind.

**Comment by rhero** [comment]
@hsaraogi can you go through and update the checklist with other things that have been completed?

I don't see this ticket as being a useful way to actually get to these specific improvements, or even as a good tracking mechanism of what's been fixed as we're more likely to file a new ticket, fix, and close it before coming back to this one.
